modLoader="javafml"
loaderVersion="[4,)"

license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
displayURL="${mod_url}"
issueTrackerURL="${mod_url}/issues"

[[mixins]]
config = "iac_p.mixins.json"

# 模组依赖声明
[[dependencies.iac_p]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iac_p]]
    modId="create"
    type="required"
    versionRange="[6.0,7.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iac_p]]
    modId="simulated"
    type="required"
    versionRange="[1.0,2.0)"
    ordering="NONE"
    side="BOTH"
